general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener { 
    timeout =  300                                              # 5min
    on-timeout = brightnessctl -s -d amdgpu_bl1 set 0
    on-resume  = brightnessctl -r -d amdgpu_bl1
}

listener {
    timeout = 600                                               # 10min
    on-timeout = hyprlock
}

listener {
    timeout = 900                                               # 15min
    on-timeout = hyprctl dispatch dpms off                      # screen off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 1800                                              # 30min
    on-timeout = systemctl suspend
}